### ISSUE TITLE
Roslyn analyzer

### ISSUE THREAD

**Issue by tebeco** [Tvde1/GuidRecycler#4]
add a roslyn analyzer detecting every guid going out of scope and emit a warning when not calling the recycler

**Comment by Tvde1** [comment]
Hello! We're grateful for your suggestion regarding the implementation of a Roslyn analyzer to detect Guids going out of scope and issue warnings for not using the recycler. It's an intriguing concept that could greatly enhance the proper usage of our package. However, I want to acknowledge that this idea is indeed quite complex and presents its own set of challenges. While it's on our backlog, I'd like to set the right expectations – due to its intricacy, it might not be something we can address in the near future. Rest assured, we're committed to exploring this possibility, and we'll keep you updated on any progress. Thank you for your understanding and for sharing your thoughts with us!
